=begin
#Bleumi Pay API

#A simple and powerful REST API to integrate ERC20 payments into your business or application

The version of the OpenAPI document: 1.0.0
Contact: info@bleumi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

module BleumiPay
  VERSION = '1.0.1'
end
