=begin
#Bleumi Pay API

#A simple and powerful REST API to integrate ERC20 payments into your business or application

The version of the OpenAPI document: 1.0.0
Contact: info@bleumi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

require 'date'

module BleumiPay
  class EthNetwork
    MAINNET = "mainnet".freeze
    ROPSTEN = "ropsten".freeze
    GOERLI = "goerli".freeze
    KOVAN = "kovan".freeze
    RINKEBY = "rinkeby".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = EthNetwork.constants.select { |c| EthNetwork::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #EthNetwork" if constantValues.empty?
      value
    end
  end
end
