# -*- encoding: utf-8 -*-

=begin
#Bleumi Pay API

#A simple and powerful REST API to integrate ERC20 payments into your business or application

The version of the OpenAPI document: 1.0.0
Contact: info@bleumi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "bleumi_pay_sdk_ruby/version"

Gem::Specification.new do |s|
  s.name        = "bleumi_pay_sdk_ruby"
  s.version     = BleumiPay::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Bleumi"]
  s.email       = ["info@bleumi.com"]
  s.homepage    = "https://pay.bleumi.com/"
  s.summary     = "Bleumi Pay API Ruby Gem"
  s.description = "A simple and powerful REST API to integrate ERC20 payments into your business or application"
  s.license     = "MIT"
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
  s.metadata    = { "source_code_uri" => "https://github.com/bleumi/bleumi-pay-sdk-ruby" }
end
