=begin
#Bleumi Pay REST API

#A simple and powerful REST API to integrate Algorand, Ethereum, ERC-20 and xDai payments and/or payouts into your business

The version of the OpenAPI document: 1.0.0
Contact: info@bleumi.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for BleumiPay::AlgorandWalletAddress
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AlgorandWalletAddress' do
  before do
    # run before each test
    @instance = BleumiPay::AlgorandWalletAddress.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AlgorandWalletAddress' do
    it 'should create an instance of AlgorandWalletAddress' do
      expect(@instance).to be_instance_of(BleumiPay::AlgorandWalletAddress)
    end
  end
  describe 'test attribute "addr"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "inputs"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
